// games/siapa/events.js
// Standard Game Events for SIAPA Survival Livechat Game

module.exports = {
    GAME_STARTED: "GAME_STARTED",
    LOBBY_START: "LOBBY_START",
    LOBBY_COUNTDOWN: "LOBBY_COUNTDOWN",
    LOBBY_CLOSED: "LOBBY_CLOSED",
    PLAYER_JOINED: "PLAYER_JOINED",
    ROUND_STARTED: "ROUND_STARTED",
    CHALLENGE_START: "CHALLENGE_START",
    CHALLENGE_TICK: "CHALLENGE_TICK",
    PLAYER_ELIMINATED: "PLAYER_ELIMINATED",
    ROUND_COMPLETED: "ROUND_COMPLETED",
    FINAL_STARTED: "FINAL_STARTED",
    FINAL_DUEL: "FINAL_DUEL",
    WINNER: "WINNER",
    GAME_ENDED: "GAME_ENDED",
    GAME_STOPPED: "GAME_STOPPED"
};
